import { Sparkles, Zap, Star, Palette, Video, Wand2, ImageUp, Film, LucideIcon } from "lucide-react"
import { Square, RectangleVertical, RectangleHorizontal } from "lucide-react"
import { BlackForestLabsIcon } from "@/components/icons/black-forest-labs-icon"
import type React from "react"

export interface ModelInfo {
  id: string
  name: string
  description: string
  icon: LucideIcon | React.ComponentType<{ className?: string }>
  provider: string
  gradient: string
  type?: "image" | "video"
  category?: "text-to-image" | "text-to-video" | "image-to-video" | "image-to-image"
  credits?: number
  credits_flat?: number
  credits_per_5sec?: number
  pricing_type?: 'variable'
  pricing_unit?: string
  recommended?: boolean
  thumbnailUrl?: string
  thumbnailAnimatedUrl?: string
  tags?: string[]
  highlighted?: boolean
  pinned?: boolean
}

export interface AspectRatioInfo {
  label: string
  ratio: string
  width: number
  height: number
  icon: LucideIcon
}

// ============================================
// IMAGE MODELS (Text-to-Image)
// ============================================
export const IMAGE_MODELS: ModelInfo[] = [
  {
    id: "fal-ai/flux-pro/v1.1-ultra",
    name: "FLUX 1.1 Pro Ultra",
    description: "Professional-grade image quality with up to 2K resolution and improved photo realism.",
    icon: BlackForestLabsIcon,
    provider: "Black Forest Labs",
    gradient: "linear-gradient(to right, rgb(139, 92, 246), rgb(217, 70, 239))",
    category: "text-to-image",
    credits: 2,
    recommended: true,
    highlighted: true,
    tags: ["high-res", "realism", "premium"],
    thumbnailUrl: "/model-thumbnails/fal_ai_flux_pro_v1_1_ultra_flux-pro-v1-1-ultra.webp",
  },
  {
    id: "fal-ai/flux-pro/v1.1",
    name: "FLUX 1.1 Pro",
    description: "Professional quality with fast generation. Great all-rounder.",
    icon: BlackForestLabsIcon,
    provider: "Black Forest Labs",
    gradient: "linear-gradient(to right, rgb(99, 102, 241), rgb(168, 85, 247))",
    category: "text-to-image",
    credits: 1,
    recommended: true,
    highlighted: true,
    tags: ["fast", "quality", "versatile"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/flux-pro-fal.webp",
  },
  {
    id: "fal-ai/flux/dev",
    name: "FLUX.1 [dev]",
    description: "12B parameter flow transformer for high-quality images. Great for personal and commercial use.",
    icon: BlackForestLabsIcon,
    provider: "Black Forest Labs",
    gradient: "linear-gradient(to right, rgb(59, 130, 246), rgb(6, 182, 212))",
    category: "text-to-image",
    credits: 1,
    highlighted: true,
    tags: ["versatile", "popular"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Upscale-1.jpeg",
  },
  {
    id: "fal-ai/flux-2",
    name: "FLUX 2",
    description: "Next generation FLUX model with improved quality and speed.",
    icon: BlackForestLabsIcon,
    provider: "Black Forest Labs",
    gradient: "linear-gradient(to right, rgb(99, 102, 241), rgb(168, 85, 247))",
    category: "text-to-image",
    credits: 1,
    highlighted: true,
    tags: ["fast", "high-quality"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Upscale-1.jpeg",
  },
  {
    id: "fal-ai/flux-2-pro",
    name: "FLUX 2 Pro",
    description: "Professional variant of FLUX 2 with enhanced capabilities.",
    icon: BlackForestLabsIcon,
    provider: "Black Forest Labs",
    gradient: "linear-gradient(to right, rgb(139, 92, 246), rgb(217, 70, 239))",
    category: "text-to-image",
    credits: 2,
    highlighted: true,
    tags: ["premium", "professional"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Upscale-1.jpeg",
  },
  {
    id: "fal-ai/recraft/v3/text-to-image",
    name: "Recraft V3",
    description: "SOTA image generation with long text rendering, vector art, and brand style support.",
    icon: Palette,
    provider: "Recraft",
    gradient: "linear-gradient(to right, rgb(236, 72, 153), rgb(244, 63, 94))",
    category: "text-to-image",
    credits: 1,
    highlighted: true,
    tags: ["vector", "typography", "style"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/recraft-v3.webp",
  },
  {
    id: "fal-ai/ideogram/v2",
    name: "Ideogram V2",
    description: "Exceptional typography handling with realistic outputs for commercial and creative use.",
    icon: Star,
    provider: "Ideogram",
    gradient: "linear-gradient(to right, rgb(251, 146, 60), rgb(249, 115, 22))",
    category: "text-to-image",
    credits: 2,
    highlighted: true,
    tags: ["typography", "realism", "logos"],
    thumbnailUrl: "https://fal.media/files/monkey/8WNQdDJ1eYpnl12jwhCjT_c9879f96533a47ae82e07946a67b0c8c.jpg",
  },
  {
    id: "fal-ai/stable-diffusion-v35-large",
    name: "Stable Diffusion 3.5 Large",
    description: "MMDiT model with improved typography, prompt understanding, and resource efficiency.",
    icon: Sparkles,
    provider: "Stability AI",
    gradient: "linear-gradient(to right, rgb(34, 197, 94), rgb(16, 185, 129))",
    category: "text-to-image",
    credits: 1,
    highlighted: true,
    tags: ["diffusion", "typography", "style"],
    thumbnailUrl: "/model-thumbnails/fal_ai_stable_diffusion_v35_large_Bi6nsyNxslnu2SfI3jtkZ_e52ae7331ca94401bce20e695e3838a8.jpg",
  },
  {
    id: "fal-ai/imagen4/preview",
    name: "Imagen 4",
    description: "Google's highest quality image generation model.",
    icon: Sparkles,
    provider: "Google",
    gradient: "linear-gradient(to right, rgb(66, 133, 244), rgb(234, 67, 53))",
    category: "text-to-image",
    credits: 2,
    highlighted: true,
    tags: ["google", "premium"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Sound-3.jpg",
  },
  {
    id: "fal-ai/imagen4/preview/fast",
    name: "Imagen 4 Fast",
    description: "Google's highest quality image generation model - fast variant.",
    icon: Zap,
    provider: "Google",
    gradient: "linear-gradient(to right, rgb(66, 133, 244), rgb(52, 168, 83))",
    category: "text-to-image",
    credits: 1,
    highlighted: true,
    tags: ["google", "fast"],
    thumbnailUrl: "https://v3b.fal.media/files/b/lion/wOlG7nOgvzkPiOfnMUAnD_1088439693f7466ba053cadb887f4191.jpg",
  },
  {
    id: "fal-ai/hidream-i1-full",
    name: "HiDream I1 Full",
    description: "Open-source 17B parameter model achieving state-of-the-art image quality.",
    icon: Sparkles,
    provider: "HiDream",
    gradient: "linear-gradient(to right, rgb(168, 85, 247), rgb(236, 72, 153))",
    category: "text-to-image",
    credits: 1,
    highlighted: true,
    tags: ["open-source", "high-quality"],
    thumbnailUrl: "https://fal.media/files/monkey/HzdkkAoX8-PqrYZUV0zOW_1efb1b99d0e84ce78dd35e8edc69fe09.jpg",
  },
  {
    id: "fal-ai/hidream-i1-fast",
    name: "HiDream I1 Fast",
    description: "Fast 17B parameter model with SOTA quality in just 16 steps.",
    icon: Zap,
    provider: "HiDream",
    gradient: "linear-gradient(to right, rgb(168, 85, 247), rgb(59, 130, 246))",
    category: "text-to-image",
    credits: 1,
    highlighted: true,
    tags: ["fast", "efficient"],
    thumbnailUrl: "https://fal.media/files/zebra/Ua1DJkXRU7nz46GKt6x5R_7b333b5e26bd413aa5d65d1959878828.jpg",
  },
  {
    id: "fal-ai/gemini-3-pro-image-preview",
    name: "Gemini 3 Pro",
    description: "Google's Gemini 3 Pro image generation model.",
    icon: Sparkles,
    provider: "Google",
    gradient: "linear-gradient(to right, rgb(66, 133, 244), rgb(251, 188, 5))",
    category: "text-to-image",
    credits: 2,
    highlighted: true,
    tags: ["google", "premium"],
    thumbnailUrl: "/model-thumbnails/fal_ai_imagen4_preview_Sound-3.jpg",
  },
  {
    id: "fal-ai/flux-lora",
    name: "FLUX.1 LoRA",
    description: "FLUX with LoRA support for custom styles and fine-tuned outputs.",
    icon: BlackForestLabsIcon,
    provider: "Black Forest Labs",
    gradient: "linear-gradient(to right, rgb(59, 130, 246), rgb(168, 85, 247))",
    category: "text-to-image",
    credits: 1,
    highlighted: true,
    tags: ["lora", "customizable"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/flux-lora.webp",
  },
  {
    id: "bria/text-to-image/3.2",
    name: "Bria 3.2",
    description: "Trained exclusively on licensed data for safe commercial use. Excels in text rendering.",
    icon: Sparkles,
    provider: "Bria",
    gradient: "linear-gradient(to right, rgb(59, 130, 246), rgb(34, 197, 94))",
    category: "text-to-image",
    credits: 1,
    highlighted: true,
    tags: ["commercial-safe", "typography"],
    thumbnailUrl: "https://fal.media/files/monkey/EZR7hDbrO6DQ_MP-BYQPt_8bb97804d8fc4f21863b457a061b5f8a.jpg",
  },
  {
    id: "fal-ai/luma-photon",
    name: "Luma Photon",
    description: "Most creative and personalizable visual model with step-function cost efficiency.",
    icon: Sparkles,
    provider: "Luma",
    gradient: "linear-gradient(to right, rgb(251, 146, 60), rgb(236, 72, 153))",
    category: "text-to-image",
    credits: 1,
    highlighted: false,
    tags: ["creative", "efficient"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/luma-photon.webp",
  },
  {
    id: "fal-ai/fast-sdxl",
    name: "Stable Diffusion XL",
    description: "Run SDXL at lightning speed with LoRA and embedding support.",
    icon: Sparkles,
    provider: "Stability AI",
    gradient: "linear-gradient(to right, rgb(34, 197, 94), rgb(59, 130, 246))",
    category: "text-to-image",
    credits: 1,
    highlighted: false,
    tags: ["diffusion", "fast", "lora"],
    thumbnailUrl: "/model-thumbnails/fal_ai_fast_sdxl_fast-sdxl.jpeg",
  },
]

// ============================================
// VIDEO MODELS (Text-to-Video)
// ============================================
export const VIDEO_MODELS: ModelInfo[] = [
  {
    id: "fal-ai/veo3",
    name: "Veo 3",
    description: "Google's most advanced AI video generation model with sound.",
    icon: Video,
    provider: "Google",
    gradient: "linear-gradient(to right, rgb(66, 133, 244), rgb(234, 67, 53))",
    type: "video",
    category: "text-to-video",
    credits: 8,
    recommended: true,
    highlighted: true,
    tags: ["google", "premium", "audio"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Sound-2.jpg",
  },
  {
    id: "fal-ai/veo3/fast",
    name: "Veo 3 Fast",
    description: "Faster, more cost-effective version of Veo 3.",
    icon: Zap,
    provider: "Google",
    gradient: "linear-gradient(to right, rgb(66, 133, 244), rgb(52, 168, 83))",
    type: "video",
    category: "text-to-video",
    credits: 5,
    highlighted: true,
    tags: ["google", "fast", "audio"],
    thumbnailUrl: "/video-thumbnails/veo3-fast-thumb.mp4",
  },
  {
    id: "fal-ai/veo3.1",
    name: "Veo 3.1",
    description: "Latest Veo model with enhanced quality and capabilities.",
    icon: Video,
    provider: "Google",
    gradient: "linear-gradient(to right, rgb(66, 133, 244), rgb(251, 188, 5))",
    type: "video",
    category: "text-to-video",
    credits: 10,
    recommended: true,
    highlighted: true,
    tags: ["google", "premium"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Sound-2.jpg",
  },
  {
    id: "fal-ai/kling-video/v2.1/master/text-to-video",
    name: "Kling 2.1 Master",
    description: "Premium Kling model for professional video generation.",
    icon: Video,
    provider: "Kuaishou",
    gradient: "linear-gradient(to right, rgb(124, 58, 237), rgb(139, 92, 246))",
    type: "video",
    category: "text-to-video",
    credits: 5,
    recommended: true,
    highlighted: true,
    tags: ["premium", "master"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Upscale-5.jpeg",
  },
  {
    id: "fal-ai/kling-video/v2.5-turbo/pro/text-to-video",
    name: "Kling 2.5 Turbo Pro",
    description: "Top-tier text-to-video with unparalleled motion fluidity and cinematic visuals.",
    icon: Zap,
    provider: "Kuaishou",
    gradient: "linear-gradient(to right, rgb(139, 92, 246), rgb(236, 72, 153))",
    type: "video",
    category: "text-to-video",
    credits: 6,
    highlighted: true,
    tags: ["cinematic", "motion", "premium"],
    thumbnailUrl: "https://v3.fal.media/files/panda/6YaK9lV7ySsUA9I3dUp5r_8a807b0c8e2641db9e345107ab8a809e.jpg",
  },
  {
    id: "fal-ai/sora-2/text-to-video",
    name: "Sora 2",
    description: "OpenAI's advanced text-to-video model.",
    icon: Video,
    provider: "OpenAI",
    gradient: "linear-gradient(to right, rgb(16, 163, 127), rgb(59, 130, 246))",
    type: "video",
    category: "text-to-video",
    credits: 8,
    highlighted: true,
    tags: ["openai", "premium"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Sound-2.jpg",
  },
  {
    id: "fal-ai/minimax/video-01",
    name: "MiniMax Video 01",
    description: "High quality video clips with great motion coherence.",
    icon: Video,
    provider: "MiniMax",
    gradient: "linear-gradient(to right, rgb(59, 130, 246), rgb(37, 99, 235))",
    type: "video",
    category: "text-to-video",
    credits: 4,
    highlighted: false,
    tags: ["motion", "coherent"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/minimax-video-01-image-to-video.webp",
  },
  {
    id: "fal-ai/minimax/hailuo-02/standard/text-to-video",
    name: "MiniMax Hailuo 02",
    description: "Advanced video generation with 768p resolution.",
    icon: Video,
    provider: "MiniMax",
    gradient: "linear-gradient(to right, rgb(59, 130, 246), rgb(99, 102, 241))",
    type: "video",
    category: "text-to-video",
    credits: 4,
    highlighted: true,
    tags: ["768p", "standard"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/for%20videos-1.jpg",
  },
  {
    id: "fal-ai/minimax/hailuo-2.3/pro/text-to-video",
    name: "MiniMax Hailuo 2.3 Pro",
    description: "Professional-grade 1080p video generation.",
    icon: Video,
    provider: "MiniMax",
    gradient: "linear-gradient(to right, rgb(99, 102, 241), rgb(139, 92, 246))",
    type: "video",
    category: "text-to-video",
    credits: 6,
    highlighted: true,
    tags: ["1080p", "premium"],
    thumbnailUrl: "https://v3b.fal.media/files/b/elephant/j3hSIKLqmWT7NXmIwTUQ0_1ec8fc1d7a53473fac7c2892ff459693.jpg",
  },
  {
    id: "fal-ai/wan-25-preview/text-to-video",
    name: "Wan 2.5",
    description: "High-quality video generation with excellent motion.",
    icon: Video,
    provider: "Alibaba",
    gradient: "linear-gradient(to right, rgb(236, 72, 153), rgb(139, 92, 246))",
    type: "video",
    category: "text-to-video",
    credits: 4,
    highlighted: true,
    tags: ["motion", "quality"],
    thumbnailUrl: "https://v3.fal.media/files/rabbit/jryVrAZdQNdLdN_4rTlN7_9bebc94cb69a482fb4d948bdd06d6a5e.jpg",
  },
  {
    id: "fal-ai/luma-dream-machine/ray-2",
    name: "Luma Ray 2",
    description: "High-fidelity video generation with realistic motion.",
    icon: Video,
    provider: "Luma",
    gradient: "linear-gradient(to right, rgb(251, 146, 60), rgb(236, 72, 153))",
    type: "video",
    category: "text-to-video",
    credits: 5,
    highlighted: true,
    tags: ["realistic", "motion"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/luma-dream-machine-ray-2.webp",
  },
  {
    id: "fal-ai/luma-dream-machine",
    name: "Luma Dream Machine",
    description: "Creative video generation with unique visual styles.",
    icon: Video,
    provider: "Luma",
    gradient: "linear-gradient(to right, rgb(251, 146, 60), rgb(168, 85, 247))",
    type: "video",
    category: "text-to-video",
    credits: 4,
    highlighted: false,
    tags: ["creative", "stylized"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/red_clouds.jpg",
  },
  {
    id: "fal-ai/hunyuan-video",
    name: "Hunyuan Video",
    description: "Open model with high visual quality, motion diversity and text alignment.",
    icon: Video,
    provider: "Tencent",
    gradient: "linear-gradient(to right, rgb(59, 130, 246), rgb(16, 185, 129))",
    type: "video",
    category: "text-to-video",
    credits: 3,
    highlighted: false,
    tags: ["open-source", "motion"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/hunyuan-video.webp",
  },
  {
    id: "fal-ai/ltxv-2/text-to-video",
    name: "LTX Video 2",
    description: "Latest LTX model for efficient video generation.",
    icon: Video,
    provider: "Lightricks",
    gradient: "linear-gradient(to right, rgb(34, 197, 94), rgb(59, 130, 246))",
    type: "video",
    category: "text-to-video",
    credits: 2,
    highlighted: false,
    tags: ["efficient", "quality"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/model_tests/cogvideox/panda.gif.gif",
  },
  {
    id: "fal-ai/kling-video/v1.6/standard/text-to-video",
    name: "Kling 1.6 Standard",
    description: "Reliable video generation with good quality-to-cost ratio.",
    icon: Video,
    provider: "Kuaishou",
    gradient: "linear-gradient(to right, rgb(124, 58, 237), rgb(99, 102, 241))",
    type: "video",
    category: "text-to-video",
    credits: 3,
    highlighted: false,
    tags: ["standard", "reliable"],
    thumbnailUrl: "https://fal.media/files/elephant/28-vTrv3W2BT-u8_cy7mt.png",
  },
  {
    id: "fal-ai/mochi-v1",
    name: "Mochi 1",
    description: "Open SOTA video model with high-fidelity motion and prompt adherence.",
    icon: Video,
    provider: "Genmo",
    gradient: "linear-gradient(to right, rgb(168, 85, 247), rgb(59, 130, 246))",
    type: "video",
    category: "text-to-video",
    credits: 2,
    highlighted: false,
    tags: ["open-source", "motion"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/mochi-v1.webp",
  },
]

// ============================================
// IMAGE-TO-VIDEO MODELS  
// ============================================
export const IMAGE_TO_VIDEO_MODELS: ModelInfo[] = [
  {
    id: "fal-ai/veo3.1/first-last-frame-to-video",
    name: "Veo 3.1 First-Last Frame",
    description: "Create videos by defining start and end frames with Google's Veo 3.1.",
    icon: Film,
    provider: "Google",
    gradient: "linear-gradient(to right, rgb(66, 133, 244), rgb(251, 188, 5))",
    type: "video",
    category: "image-to-video",
    credits: 8,
    recommended: true,
    highlighted: true,
    tags: ["google", "premium", "frames"],
    thumbnailUrl: "/video-thumbnails/veo31-thumb.mp4",
  },
  {
    id: "fal-ai/kling-video/v2.6/pro/image-to-video",
    name: "Kling 2.6 Pro (I2V)",
    description: "Latest image-to-video with native audio generation, enhanced motion fluidity, and cinematic visuals.",
    icon: Film,
    provider: "Kuaishou",
    gradient: "linear-gradient(to right, rgb(139, 92, 246), rgb(236, 72, 153))",
    type: "video",
    category: "image-to-video",
    credits: 6,
    recommended: true,
    highlighted: true,
    pinned: true,
    tags: ["cinematic", "premium", "audio"],
    thumbnailUrl: "/video-thumbnails/kling2.6-thumb.mp4",
  },
  {
    id: "fal-ai/wan-effects",
    name: "Wan Effects",
    description: "Generate high-quality videos with popular effects from images (Cakeify, Hulk, etc.).",
    icon: Wand2,
    provider: "Alibaba",
    gradient: "linear-gradient(to right, rgb(236, 72, 153), rgb(139, 92, 246))",
    type: "video",
    category: "image-to-video",
    credits: 3,
    highlighted: true,
    tags: ["effects", "viral", "fun"],
    thumbnailUrl: "/video-thumbnails/wan-effects-thumb.mp4",
  },
  {
    id: "fal-ai/veo2/image-to-video",
    name: "Veo 2 Image-to-Video",
    description: "Create videos from images with realistic motion and high quality.",
    icon: Film,
    provider: "Google",
    gradient: "linear-gradient(to right, rgb(66, 133, 244), rgb(234, 67, 53))",
    type: "video",
    category: "image-to-video",
    credits: 6,
    highlighted: true,
    tags: ["google", "realistic", "motion"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/veo2-image-to-video.webp",
  },
  {
    id: "fal-ai/wan-pro/image-to-video",
    name: "Wan 2.1 Pro",
    description: "Premium 1080p/30fps videos up to 6 seconds with exceptional quality.",
    icon: Film,
    provider: "Alibaba",
    gradient: "linear-gradient(to right, rgb(236, 72, 153), rgb(168, 85, 247))",
    type: "video",
    category: "image-to-video",
    credits: 5,
    highlighted: true,
    tags: ["premium", "1080p", "motion"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/wan-pro-image-to-video.webp",
  },
  {
    id: "fal-ai/kling-video/v2.5-turbo/pro/image-to-video",
    name: "Kling 2.5 Turbo Pro (I2V)",
    description: "Top-tier image-to-video with cinematic visuals and motion fluidity.",
    icon: Zap,
    provider: "Kuaishou",
    gradient: "linear-gradient(to right, rgb(139, 92, 246), rgb(251, 146, 60))",
    type: "video",
    category: "image-to-video",
    credits: 5,
    highlighted: true,
    tags: ["cinematic", "premium"],
    thumbnailUrl: "https://v3.fal.media/files/rabbit/2KNBk1qkmEBXK0FLgfHCl_ee4bb1ada254433bbab296893a8636e3.jpg",
  },
  {
    id: "fal-ai/kling-video/v2.1/master/image-to-video",
    name: "Kling 2.1 Master (I2V)",
    description: "Premium endpoint for top-tier image-to-video generation.",
    icon: Film,
    provider: "Kuaishou",
    gradient: "linear-gradient(to right, rgb(124, 58, 237), rgb(139, 92, 246))",
    type: "video",
    category: "image-to-video",
    credits: 5,
    highlighted: true,
    tags: ["master", "cinematic"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Upscale-5.jpeg",
  },
  {
    id: "fal-ai/minimax/hailuo-2.3/pro/image-to-video",
    name: "MiniMax Hailuo 2.3 Pro (I2V)",
    description: "Advanced 1080p image-to-video generation.",
    icon: Film,
    provider: "MiniMax",
    gradient: "linear-gradient(to right, rgb(99, 102, 241), rgb(139, 92, 246))",
    type: "video",
    category: "image-to-video",
    credits: 5,
    highlighted: true,
    tags: ["1080p", "premium"],
    thumbnailUrl: "https://v3b.fal.media/files/b/penguin/0iV7vFj9ujGqHUqKkBesN_a65fac7d7c994f39aeedabe31db6fb2d.jpg",
  },
  {
    id: "fal-ai/wan-25-preview/image-to-video",
    name: "Wan 2.5 (I2V)",
    description: "High-quality image-to-video generation.",
    icon: Film,
    provider: "Alibaba",
    gradient: "linear-gradient(to right, rgb(236, 72, 153), rgb(139, 92, 246))",
    type: "video",
    category: "image-to-video",
    credits: 4,
    highlighted: true,
    tags: ["quality", "motion"],
    thumbnailUrl: "https://v3.fal.media/files/rabbit/jryVrAZdQNdLdN_4rTlN7_9bebc94cb69a482fb4d948bdd06d6a5e.jpg",
  },
  {
    id: "fal-ai/kling-video/v1.6/pro/image-to-video",
    name: "Kling 1.6 Pro (I2V)",
    description: "Professional image-to-video generation.",
    icon: Film,
    provider: "Kuaishou",
    gradient: "linear-gradient(to right, rgb(124, 58, 237), rgb(99, 102, 241))",
    type: "video",
    category: "image-to-video",
    credits: 4,
    highlighted: true,
    tags: ["professional", "reliable"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/kling-1-6-image-to-video.webp",
  },
  {
    id: "fal-ai/minimax/video-01/image-to-video",
    name: "MiniMax Video 01 (I2V)",
    description: "Generate video clips from images with MiniMax.",
    icon: Film,
    provider: "MiniMax",
    gradient: "linear-gradient(to right, rgb(59, 130, 246), rgb(37, 99, 235))",
    type: "video",
    category: "image-to-video",
    credits: 3,
    highlighted: false,
    tags: ["motion", "transformation"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/minimax-video-01-image-to-video.webp",
  },
  {
    id: "fal-ai/luma-dream-machine/image-to-video",
    name: "Luma Dream Machine (I2V)",
    description: "Creative image-to-video with unique visual styles.",
    icon: Film,
    provider: "Luma",
    gradient: "linear-gradient(to right, rgb(251, 146, 60), rgb(168, 85, 247))",
    type: "video",
    category: "image-to-video",
    credits: 4,
    highlighted: false,
    tags: ["creative", "stylized"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/luma-dream-machine-ray-2.webp",
  },
]

// ============================================
// IMAGE-TO-IMAGE MODELS
// ============================================
export const IMAGE_TO_IMAGE_MODELS: ModelInfo[] = [
  {
    id: "fal-ai/flux-pro/kontext",
    name: "FLUX.1 Kontext [pro]",
    description: "Seamlessly enables targeted local edits and complex scene transformations.",
    icon: ImageUp,
    provider: "Black Forest Labs",
    gradient: "linear-gradient(to right, rgb(139, 92, 246), rgb(217, 70, 239))",
    category: "image-to-image",
    credits: 2,
    highlighted: true,
    tags: ["editing", "transform"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Training-2.jpg",
  },
  {
    id: "fal-ai/flux/dev/image-to-image",
    name: "FLUX.1 [dev] Image-to-Image",
    description: "High-quality style transfers and image modifications.",
    icon: BlackForestLabsIcon,
    provider: "Black Forest Labs",
    gradient: "linear-gradient(to right, rgb(59, 130, 246), rgb(6, 182, 212))",
    category: "image-to-image",
    credits: 1,
    highlighted: true,
    tags: ["style-transfer", "modification"],
    thumbnailUrl: "https://fal.media/files/panda/jJ3ZxKTV6ulhHV6GKi9nZ_68430b557ef64f68bf6f0fed0e78c6f9.jpg",
  },
  {
    id: "fal-ai/clarity-upscaler",
    name: "Clarity Upscaler",
    description: "High-fidelity image upscaling with detail preservation.",
    icon: ImageUp,
    provider: "FAL",
    gradient: "linear-gradient(to right, rgb(34, 197, 94), rgb(59, 130, 246))",
    category: "image-to-image",
    credits: 1,
    highlighted: true,
    tags: ["upscaling", "enhancement"],
    thumbnailUrl: "https://storage.googleapis.com/falserverless/gallery/controlnet-tile-upscaler.webp",
  },
  {
    id: "fal-ai/aura-sr",
    name: "AuraSR",
    description: "Fast and efficient image upscaling.",
    icon: Zap,
    provider: "FAL",
    gradient: "linear-gradient(to right, rgb(251, 146, 60), rgb(34, 197, 94))",
    category: "image-to-image",
    credits: 1,
    highlighted: true,
    tags: ["upscaling", "fast"],
    thumbnailUrl: "https://v3.fal.media/files/koala/rW7Rhmjtkjvb8gnOPUhNN_b14088de7d684d4b8489db59d53ae3f7.jpg",
  },
  {
    id: "fal-ai/flux-2/edit",
    name: "FLUX 2 Edit",
    description: "Powerful image editing with FLUX 2.",
    icon: BlackForestLabsIcon,
    provider: "Black Forest Labs",
    gradient: "linear-gradient(to right, rgb(99, 102, 241), rgb(168, 85, 247))",
    category: "image-to-image",
    credits: 2,
    highlighted: true,
    tags: ["editing", "transform"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Upscale-1.jpeg",
  },
  {
    id: "fal-ai/qwen-image-edit",
    name: "Qwen Image Edit",
    description: "Advanced image editing with natural language instructions.",
    icon: Wand2,
    provider: "Alibaba",
    gradient: "linear-gradient(to right, rgb(236, 72, 153), rgb(59, 130, 246))",
    category: "image-to-image",
    credits: 1,
    highlighted: true,
    tags: ["editing", "ai-powered"],
    thumbnailUrl: "https://storage.googleapis.com/fal_cdn/fal/Training-2.jpg",
  },
  {
    id: "simalabs/sima-upscaler",
    name: "Sima Upscaler",
    description: "Blazingly fast image upscaling.",
    icon: Zap,
    provider: "Sima Labs",
    gradient: "linear-gradient(to right, rgb(59, 130, 246), rgb(34, 197, 94))",
    category: "image-to-image",
    credits: 1,
    highlighted: true,
    tags: ["upscaling", "fast"],
    thumbnailUrl: "https://v3b.fal.media/files/b/lion/2H9bdDBfBM3q9Sj3E5blN_fbc5afeb35f74c70b5065872ef81efca.jpg",
  },
  {
    id: "fal-ai/ideogram/character",
    name: "Ideogram Character",
    description: "Generate consistent characters across images.",
    icon: Star,
    provider: "Ideogram",
    gradient: "linear-gradient(to right, rgb(251, 146, 60), rgb(249, 115, 22))",
    category: "image-to-image",
    credits: 2,
    highlighted: true,
    tags: ["character", "consistency"],
    thumbnailUrl: "https://fal.media/files/monkey/8WNQdDJ1eYpnl12jwhCjT_c9879f96533a47ae82e07946a67b0c8c.jpg",
  },
  {
    id: "fal-ai/gemini-3-pro-image-preview/edit",
    name: "Gemini 3 Pro Edit",
    description: "Google's Gemini 3 Pro for image editing and transformation.",
    icon: Sparkles,
    provider: "Google",
    gradient: "linear-gradient(to right, rgb(66, 133, 244), rgb(251, 188, 5))",
    category: "image-to-image",
    credits: 3,
    highlighted: true,
    pinned: true,
    tags: ["google", "editing", "premium"],
    thumbnailUrl: "/model-thumbnails/fal_ai_imagen4_preview_Sound-3.jpg",
  },
]

// ============================================
// ALL MODELS COMBINED
// ============================================
export const ALL_IMAGE_MODELS = [...IMAGE_MODELS, ...IMAGE_TO_IMAGE_MODELS]
export const ALL_VIDEO_MODELS = [...VIDEO_MODELS, ...IMAGE_TO_VIDEO_MODELS]

export const ASPECT_RATIOS: AspectRatioInfo[] = [
  { label: "Square", ratio: "1:1", width: 1024, height: 1024, icon: Square },
  { label: "Portrait", ratio: "2:3", width: 832, height: 1216, icon: RectangleVertical },
  { label: "Landscape", ratio: "16:9", width: 1344, height: 768, icon: RectangleHorizontal },
  { label: "Vertical", ratio: "9:16", width: 768, height: 1344, icon: RectangleVertical },
]

// WAN Effects only supports specific aspect ratios
export const WAN_ASPECT_RATIOS: AspectRatioInfo[] = [
  { label: "Square", ratio: "1:1", width: 1024, height: 1024, icon: Square },
  { label: "Landscape", ratio: "16:9", width: 1344, height: 768, icon: RectangleHorizontal },
  { label: "Vertical", ratio: "9:16", width: 768, height: 1344, icon: RectangleVertical },
]

// Veo 3 only supports 16:9 and 9:16
export const VEO_ASPECT_RATIOS: AspectRatioInfo[] = [
  { label: "Landscape", ratio: "16:9", width: 1344, height: 768, icon: RectangleHorizontal },
  { label: "Vertical", ratio: "9:16", width: 768, height: 1344, icon: RectangleVertical },
]
