// lib/models-data.ts

export type ModelCategory = 'text-to-image' | 'text-to-video' | 'image-to-image' | 'image-to-video'

export interface Model {
  id: string
  name: string
  description: string
  category: ModelCategory
  tags: string[]
  thumbnailUrl: string
  thumbnailAnimatedUrl?: string
  highlighted: boolean
  pinned?: boolean
  licenseType?: string
}

export const models: Model[] = [
  // ==================== TEXT TO IMAGE ====================
  {
    id: 'fal-ai/flux-pro/v1.1-ultra',
    name: 'FLUX1.1 [pro] ultra',
    description: 'Professional-grade image quality with up to 2K resolution and improved photo realism.',
    category: 'text-to-image',
    tags: ['high-res', 'realism', 'premium'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/flux-pro-v1-1-ultra.webp',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/recraft/v3/text-to-image',
    name: 'Recraft V3',
    description: 'SOTA image generation with long text rendering, vector art, and brand style support.',
    category: 'text-to-image',
    tags: ['vector', 'typography', 'style'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/recraft-v3.webp',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'bria/text-to-image/3.2',
    name: 'Bria 3.2',
    description: 'Trained exclusively on licensed data for safe commercial use. Excels in text rendering.',
    category: 'text-to-image',
    tags: ['commercial-safe', 'typography'],
    thumbnailUrl: 'https://fal.media/files/monkey/EZR7hDbrO6DQ_MP-BYQPt_8bb97804d8fc4f21863b457a061b5f8a.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/imagen4/preview/fast',
    name: 'Imagen 4 Fast',
    description: "Google's highest quality image generation model - fast variant.",
    category: 'text-to-image',
    tags: ['google', 'fast'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/lion/wOlG7nOgvzkPiOfnMUAnD_1088439693f7466ba053cadb887f4191.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/imagen4/preview',
    name: 'Imagen 4',
    description: "Google's highest quality image generation model.",
    category: 'text-to-image',
    tags: ['google', 'premium'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Sound-3.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/hidream-i1-full',
    name: 'HiDream I1 Full',
    description: 'Open-source 17B parameter model achieving state-of-the-art image quality.',
    category: 'text-to-image',
    tags: ['open-source', 'high-quality'],
    thumbnailUrl: 'https://fal.media/files/monkey/HzdkkAoX8-PqrYZUV0zOW_1efb1b99d0e84ce78dd35e8edc69fe09.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/hidream-i1-fast',
    name: 'HiDream I1 Fast',
    description: 'Fast 17B parameter model with SOTA quality in just 16 steps.',
    category: 'text-to-image',
    tags: ['fast', 'efficient'],
    thumbnailUrl: 'https://fal.media/files/zebra/Ua1DJkXRU7nz46GKt6x5R_7b333b5e26bd413aa5d65d1959878828.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/flux/dev',
    name: 'FLUX.1 [dev]',
    description: '12B parameter flow transformer for high-quality images. Great for personal and commercial use.',
    category: 'text-to-image',
    tags: ['versatile', 'popular'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Upscale-1.jpeg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/ideogram/v2',
    name: 'Ideogram V2',
    description: 'Exceptional typography handling with realistic outputs for commercial and creative use.',
    category: 'text-to-image',
    tags: ['typography', 'realism', 'logos'],
    thumbnailUrl: 'https://fal.media/files/monkey/8WNQdDJ1eYpnl12jwhCjT_c9879f96533a47ae82e07946a67b0c8c.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/stable-diffusion-v35-large',
    name: 'Stable Diffusion 3.5 Large',
    description: 'MMDiT model with improved typography, prompt understanding, and resource efficiency.',
    category: 'text-to-image',
    tags: ['diffusion', 'typography', 'style'],
    thumbnailUrl: 'https://fal.media/files/zebra/Bi6nsyNxslnu2SfI3jtkZ_e52ae7331ca94401bce20e695e3838a8.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/flux-lora',
    name: 'FLUX.1 LoRA',
    description: 'FLUX with LoRA support for custom styles and fine-tuned outputs.',
    category: 'text-to-image',
    tags: ['lora', 'customizable'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/flux-lora.webp',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/gemini-3-pro-image-preview',
    name: 'Gemini 3 Pro',
    description: "Google's Gemini 3 Pro image generation model.",
    category: 'text-to-image',
    tags: ['google', 'premium'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Sound-3.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/flux-2',
    name: 'FLUX 2',
    description: 'Next generation FLUX model with improved quality and speed.',
    category: 'text-to-image',
    tags: ['fast', 'high-quality'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Upscale-1.jpeg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/flux-2-pro',
    name: 'FLUX 2 Pro',
    description: 'Professional variant of FLUX 2 with enhanced capabilities.',
    category: 'text-to-image',
    tags: ['premium', 'professional'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Upscale-1.jpeg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/luma-photon',
    name: 'Luma Photon',
    description: 'Most creative and personalizable visual model with step-function cost efficiency.',
    category: 'text-to-image',
    tags: ['creative', 'efficient'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/luma-photon.webp',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/fast-sdxl',
    name: 'Stable Diffusion XL',
    description: 'Run SDXL at lightning speed with LoRA and embedding support.',
    category: 'text-to-image',
    tags: ['diffusion', 'fast', 'lora'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/fast-sdxl.jpeg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/playground-v25',
    name: 'Playground v2.5',
    description: 'State-of-the-art open-source model optimized for aesthetic quality.',
    category: 'text-to-image',
    tags: ['artistic', 'style', 'open-source'],
    thumbnailUrl: 'https://fal-cdn.batuhan-941.workers.dev/files/monkey/8WXjrk5HEam79CPlQlo5T.jpeg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/kolors',
    name: 'Kolors',
    description: 'Photorealistic text-to-image generation.',
    category: 'text-to-image',
    tags: ['realism', 'diffusion'],
    thumbnailUrl: 'https://v2.fal.media/files/bdcf6a7a3f4146c39555e0c195715e65_73e054513f15488f93248ae10d67ece5.png',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/sana',
    name: 'Sana',
    description: 'Ultra-fast 4K image synthesis in under a second with strong text alignment.',
    category: 'text-to-image',
    tags: ['fast', '4k', 'high-res'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/sana.webp',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/pixart-sigma',
    name: 'PixArt-Σ',
    description: 'Diffusion Transformer for 4K text-to-image generation.',
    category: 'text-to-image',
    tags: ['diffusion', '4k'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/pixart-sigma.jpeg',
    highlighted: false,
  },

  // ==================== TEXT TO VIDEO ====================
  {
    id: 'fal-ai/veo3',
    name: 'Veo 3',
    description: "Google's most advanced AI video generation model with sound.",
    category: 'text-to-video',
    tags: ['google', 'premium', 'audio'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Sound-2.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/veo3/fast',
    name: 'Veo 3 Fast',
    description: 'Faster, more cost-effective version of Veo 3.',
    category: 'text-to-video',
    tags: ['google', 'fast', 'audio'],
    thumbnailUrl: '/video-thumbnails/veo3-fast-thumb.mp4',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/veo3.1',
    name: 'Veo 3.1',
    description: 'Latest Veo model with enhanced quality and capabilities.',
    category: 'text-to-video',
    tags: ['google', 'premium'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Sound-2.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/kling-video/v2.5-turbo/pro/text-to-video',
    name: 'Kling 2.5 Turbo Pro',
    description: 'Top-tier text-to-video with unparalleled motion fluidity and cinematic visuals.',
    category: 'text-to-video',
    tags: ['cinematic', 'motion', 'premium'],
    thumbnailUrl: 'https://v3.fal.media/files/panda/6YaK9lV7ySsUA9I3dUp5r_8a807b0c8e2641db9e345107ab8a809e.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/kling-video/v2/master/text-to-video',
    name: 'Kling 2.0 Master',
    description: 'Premium Kling model for professional video generation.',
    category: 'text-to-video',
    tags: ['premium', 'master'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Upscale-5.jpeg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/kling-video/v1.6/standard/text-to-video',
    name: 'Kling 1.6 Standard',
    description: 'Reliable video generation with good quality-to-cost ratio.',
    category: 'text-to-video',
    tags: ['standard', 'reliable'],
    thumbnailUrl: 'https://fal.media/files/elephant/28-vTrv3W2BT-u8_cy7mt.png',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/sora-2/text-to-video',
    name: 'Sora 2',
    description: "OpenAI's advanced text-to-video model.",
    category: 'text-to-video',
    tags: ['openai', 'premium'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Sound-2.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/minimax/hailuo-02/standard/text-to-video',
    name: 'MiniMax Hailuo 02',
    description: 'Advanced video generation with 768p resolution.',
    category: 'text-to-video',
    tags: ['768p', 'standard'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/for%20videos-1.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/minimax/hailuo-2.3/pro/text-to-video',
    name: 'MiniMax Hailuo 2.3 Pro',
    description: 'Professional-grade 1080p video generation.',
    category: 'text-to-video',
    tags: ['1080p', 'premium'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/elephant/j3hSIKLqmWT7NXmIwTUQ0_1ec8fc1d7a53473fac7c2892ff459693.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/wan-25-preview/text-to-video',
    name: 'Wan 2.5',
    description: 'High-quality video generation with excellent motion.',
    category: 'text-to-video',
    tags: ['motion', 'quality'],
    thumbnailUrl: 'https://v3.fal.media/files/rabbit/jryVrAZdQNdLdN_4rTlN7_9bebc94cb69a482fb4d948bdd06d6a5e.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/ltxv-2/text-to-video',
    name: 'LTX Video 2',
    description: 'Latest LTX model for efficient video generation.',
    category: 'text-to-video',
    tags: ['efficient', 'quality'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/model_tests/cogvideox/panda.gif.gif',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/longcat-video/text-to-video/720p',
    name: 'LongCat Video 720p',
    description: 'Generate long videos in 720p/30fps from text.',
    category: 'text-to-video',
    tags: ['long-form', '720p'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/panda/CY4FlHWoLckmlvvquFUeu_b3840719e081495983b5fe1d2648f0fb.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/longcat-video/distilled/text-to-video/720p',
    name: 'LongCat Distilled 720p',
    description: 'Fast, distilled variant for efficient long video generation.',
    category: 'text-to-video',
    tags: ['fast', 'distilled', 'budget'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/panda/LG1BXVYrhBm6J6Dnv4zAP_ee476e357e4e4bc7bcff9a7812d16c1b.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/hunyuan-video',
    name: 'Hunyuan Video',
    description: 'Open model with high visual quality, motion diversity and text alignment.',
    category: 'text-to-video',
    tags: ['open-source', 'motion'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/hunyuan-video.webp',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/luma-dream-machine',
    name: 'Luma Dream Machine',
    description: 'Creative video generation with unique visual styles.',
    category: 'text-to-video',
    tags: ['creative', 'stylized'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/red_clouds.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/luma-dream-machine/ray-2',
    name: 'Luma Ray 2',
    description: 'High-fidelity video generation with realistic motion.',
    category: 'text-to-video',
    tags: ['realistic', 'motion'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/luma-dream-machine-ray-2.webp',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/mochi-v1',
    name: 'Mochi 1',
    description: 'Open SOTA video model with high-fidelity motion and prompt adherence.',
    category: 'text-to-video',
    tags: ['open-source', 'motion'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/mochi-v1.webp',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/infinity-star/text-to-video',
    name: 'Infinity Star',
    description: '8B autoregressive engine for crisp 720p videos - 10× faster than diffusion.',
    category: 'text-to-video',
    tags: ['fast', 'efficient'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/monkey/eo_C3d0eQJbsr5Yisn1Tg_363925b0a47242e68029c39bc698cb65.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/ltx-video',
    name: 'LTX Video',
    description: 'Budget-friendly video generation from prompts.',
    category: 'text-to-video',
    tags: ['budget', 'accessible'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/model_tests/cogvideox/panda.gif.gif',
    highlighted: false,
  },
  {
    id: 'fal-ai/fast-animatediff/text-to-video',
    name: 'AnimateDiff',
    description: 'Animate your ideas with stylized video generation.',
    category: 'text-to-video',
    tags: ['animation', 'stylized'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/fast-animatediff-t2v.webp',
    highlighted: false,
  },

  // ==================== IMAGE TO IMAGE ====================
  {
    id: 'fal-ai/flux-pro/kontext',
    name: 'FLUX.1 Kontext [pro]',
    description: 'Seamlessly enables targeted local edits and complex scene transformations.',
    category: 'image-to-image',
    tags: ['editing', 'transform'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Training-2.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/flux/dev/image-to-image',
    name: 'FLUX.1 [dev] Image-to-Image',
    description: 'High-quality style transfers and image modifications.',
    category: 'image-to-image',
    tags: ['style-transfer', 'modification'],
    thumbnailUrl: 'https://fal.media/files/panda/jJ3ZxKTV6ulhHV6GKi9nZ_68430b557ef64f68bf6f0fed0e78c6f9.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/clarity-upscaler',
    name: 'Clarity Upscaler',
    description: 'High-fidelity image upscaling with detail preservation.',
    category: 'image-to-image',
    tags: ['upscaling', 'enhancement'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/controlnet-tile-upscaler.webp',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/aura-sr',
    name: 'AuraSR',
    description: 'Fast and efficient image upscaling.',
    category: 'image-to-image',
    tags: ['upscaling', 'fast'],
    thumbnailUrl: 'https://v3.fal.media/files/koala/rW7Rhmjtkjvb8gnOPUhNN_b14088de7d684d4b8489db59d53ae3f7.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'clarityai/crystal-upscaler',
    name: 'Crystal Upscaler',
    description: 'Advanced facial detail enhancement for portrait photography.',
    category: 'image-to-image',
    tags: ['upscaling', 'portrait', 'face'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/rabbit/VjfWoUXISYQgeyKCNi8lU.png',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'simalabs/sima-upscaler',
    name: 'Sima Upscaler',
    description: 'Blazingly fast image upscaling.',
    category: 'image-to-image',
    tags: ['upscaling', 'fast'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/lion/2H9bdDBfBM3q9Sj3E5blN_fbc5afeb35f74c70b5065872ef81efca.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/qwen-image-edit',
    name: 'Qwen Image Edit',
    description: 'Advanced image editing with natural language instructions.',
    category: 'image-to-image',
    tags: ['editing', 'ai-powered'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Training-2.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/ideogram/character',
    name: 'Ideogram Character',
    description: 'Generate consistent characters across images.',
    category: 'image-to-image',
    tags: ['character', 'consistency'],
    thumbnailUrl: 'https://fal.media/files/monkey/8WNQdDJ1eYpnl12jwhCjT_c9879f96533a47ae82e07946a67b0c8c.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/flux-2/edit',
    name: 'FLUX 2 Edit',
    description: 'Powerful image editing with FLUX 2.',
    category: 'image-to-image',
    tags: ['editing', 'transform'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Upscale-1.jpeg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/hidream-e1-1',
    name: 'HiDream E1',
    description: 'High-quality image editing and transformation.',
    category: 'image-to-image',
    tags: ['editing', 'quality'],
    thumbnailUrl: 'https://fal.media/files/monkey/HzdkkAoX8-PqrYZUV0zOW_1efb1b99d0e84ce78dd35e8edc69fe09.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/bria/reimagine',
    name: 'Bria Reimagine',
    description: 'Transform sketches and photos into new illustrations while preserving structure.',
    category: 'image-to-image',
    tags: ['reimagine', 'structure'],
    thumbnailUrl: 'https://fal.media/files/rabbit/wXG4NtIA2sZUz7-CiooUJ_bb5f4b6f122149849d744baaad6896f8.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/image-editing/retouch',
    name: 'Image Retouch',
    description: 'Professional retouching for images.',
    category: 'image-to-image',
    tags: ['retouch', 'enhancement'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/for%20videos-5.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/calligrapher',
    name: 'Calligrapher',
    description: 'Modify text on images while retaining font style.',
    category: 'image-to-image',
    tags: ['typography', 'text'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Sound-1.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/flux-2-lora-gallery/virtual-tryon',
    name: 'Virtual Try-On',
    description: 'Virtual clothing try-on from person and garment images.',
    category: 'image-to-image',
    tags: ['fashion', 'try-on'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/penguin/cvM8xzdznnFvnUi2BzS6u.png',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/flux-2-lora-gallery/apartment-staging',
    name: 'Apartment Staging',
    description: 'Virtually furnish empty apartments.',
    category: 'image-to-image',
    tags: ['real-estate', 'staging'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/lion/0Tyv49_he8ViUyyChEb3D.png',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'easel-ai/fashion-tryon',
    name: 'Fashion Try-On',
    description: 'Try on clothes virtually with AI.',
    category: 'image-to-image',
    tags: ['fashion', 'try-on'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Upscale-3.jpeg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/rife',
    name: 'RIFE',
    description: 'Real-time intermediate flow estimation for image interpolation.',
    category: 'image-to-image',
    tags: ['interpolation', 'animation'],
    thumbnailUrl: 'https://fal.media/files/penguin/HLrNymdnzx1neVc9Pj0c1_debdeb10494e45888dd68d1a2df2dcac.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },

  // ==================== IMAGE TO VIDEO ====================
  {
    id: 'fal-ai/wan-effects',
    name: 'Wan Effects',
    description: 'Generate high-quality videos with popular effects from images.',
    category: 'image-to-video',
    tags: ['effects', 'motion'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/Fal_Visuals_V1_012.jpg',
    thumbnailAnimatedUrl: 'https://storage.googleapis.com/fal_cdn/Fal_Visuals_V1_101.webp',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/wan-pro/image-to-video',
    name: 'Wan 2.1 Pro',
    description: 'Premium 1080p/30fps videos up to 6 seconds with exceptional quality.',
    category: 'image-to-video',
    tags: ['premium', '1080p', 'motion'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/wan-pro-image-to-video.webp',
    thumbnailAnimatedUrl: 'https://storage.googleapis.com/falserverless/gallery/wan-pro-image-to-video-animated.webp',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/veo2/image-to-video',
    name: 'Veo 2 Image-to-Video',
    description: 'Create videos from images with realistic motion and high quality.',
    category: 'image-to-video',
    tags: ['google', 'realistic', 'motion'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/veo2-image-to-video.webp',
    thumbnailAnimatedUrl: 'https://storage.googleapis.com/falserverless/gallery/veo2-image-to-video-animated.webp',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/kling-video/v2.6/pro/image-to-video',
    name: 'Kling 2.6 Pro (I2V)',
    description: 'Latest image-to-video with native audio generation, enhanced motion fluidity, and cinematic visuals.',
    category: 'image-to-video',
    tags: ['cinematic', 'premium', 'audio'],
    thumbnailUrl: 'https://v3.fal.media/files/rabbit/2KNBk1qkmEBXK0FLgfHCl_ee4bb1ada254433bbab296893a8636e3.jpg',
    thumbnailAnimatedUrl: '/video-thumbnails/kling2.6-thumb.mp4',
    highlighted: true,
    pinned: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/kling-video/v2.5-turbo/pro/image-to-video',
    name: 'Kling 2.5 Turbo Pro (I2V)',
    description: 'Top-tier image-to-video with cinematic visuals and motion fluidity.',
    category: 'image-to-video',
    tags: ['cinematic', 'premium'],
    thumbnailUrl: 'https://v3.fal.media/files/rabbit/2KNBk1qkmEBXK0FLgfHCl_ee4bb1ada254433bbab296893a8636e3.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/kling-video/v2.1/master/image-to-video',
    name: 'Kling 2.1 Master (I2V)',
    description: 'Premium endpoint for top-tier image-to-video generation.',
    category: 'image-to-video',
    tags: ['master', 'cinematic'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Upscale-5.jpeg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/kling-video/v1.6/pro/image-to-video',
    name: 'Kling 1.6 Pro (I2V)',
    description: 'Professional image-to-video generation.',
    category: 'image-to-video',
    tags: ['professional', 'reliable'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/kling-1-6-image-to-video.webp',
    thumbnailAnimatedUrl: 'https://storage.googleapis.com/falserverless/gallery/kling-1-6-image-to-video-animated.webp',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/kling-video/v1.6/standard/image-to-video',
    name: 'Kling 1.6 Standard (I2V)',
    description: 'Standard image-to-video with good quality-to-cost ratio.',
    category: 'image-to-video',
    tags: ['standard', 'affordable'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/kling-1-6-image-to-video.webp',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/minimax/video-01/image-to-video',
    name: 'MiniMax Video 01 (I2V)',
    description: 'Generate video clips from images with MiniMax.',
    category: 'image-to-video',
    tags: ['motion', 'transformation'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/minimax-video-01-image-to-video.webp',
    thumbnailAnimatedUrl: 'https://storage.googleapis.com/falserverless/gallery/minimax-video-01-image-to-video-animated.webp',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/minimax/hailuo-02/standard/image-to-video',
    name: 'MiniMax Hailuo 02 (I2V)',
    description: 'Advanced image-to-video with 768p and 512p support.',
    category: 'image-to-video',
    tags: ['768p', 'standard'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Upscale.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/minimax/hailuo-2.3/pro/image-to-video',
    name: 'MiniMax Hailuo 2.3 Pro (I2V)',
    description: 'Advanced 1080p image-to-video generation.',
    category: 'image-to-video',
    tags: ['1080p', 'premium'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/penguin/0iV7vFj9ujGqHUqKkBesN_a65fac7d7c994f39aeedabe31db6fb2d.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/wan-25-preview/image-to-video',
    name: 'Wan 2.5 (I2V)',
    description: 'High-quality image-to-video generation.',
    category: 'image-to-video',
    tags: ['quality', 'motion'],
    thumbnailUrl: 'https://v3.fal.media/files/rabbit/jryVrAZdQNdLdN_4rTlN7_9bebc94cb69a482fb4d948bdd06d6a5e.jpg',
    highlighted: true,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/luma-dream-machine/image-to-video',
    name: 'Luma Dream Machine (I2V)',
    description: 'Creative image-to-video with unique visual styles.',
    category: 'image-to-video',
    tags: ['creative', 'stylized'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/luma-dream-machine-ray-2.webp',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/longcat-video/image-to-video/720p',
    name: 'LongCat 720p (I2V)',
    description: 'Generate long 720p/30fps videos from images.',
    category: 'image-to-video',
    tags: ['long-form', '720p'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/panda/CY4FlHWoLckmlvvquFUeu_b3840719e081495983b5fe1d2648f0fb.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/longcat-video/distilled/image-to-video/720p',
    name: 'LongCat Distilled (I2V)',
    description: 'Fast, efficient long video generation from images.',
    category: 'image-to-video',
    tags: ['fast', 'distilled', 'budget'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/panda/LG1BXVYrhBm6J6Dnv4zAP_ee476e357e4e4bc7bcff9a7812d16c1b.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/ltxv-2/image-to-video',
    name: 'LTX Video 2 (I2V)',
    description: 'Efficient image-to-video generation.',
    category: 'image-to-video',
    tags: ['efficient', 'quality'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/model_tests/cogvideox/panda.gif.gif',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/vidu/q2/image-to-video/turbo',
    name: 'Vidu Q2 Turbo (I2V)',
    description: 'Fast image-to-video generation.',
    category: 'image-to-video',
    tags: ['fast', 'turbo'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Sound-2.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/pixverse/v3.5/image-to-video',
    name: 'PixVerse 3.5 (I2V)',
    description: 'Generate high-quality video clips from images.',
    category: 'image-to-video',
    tags: ['quality', 'versatile'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/pixverse-v3.5.webp',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/pika/v2.2/image-to-video',
    name: 'Pika v2.2 (I2V)',
    description: 'High-quality image-to-video by Pika.',
    category: 'image-to-video',
    tags: ['quality', 'creative'],
    thumbnailUrl: 'https://v3b.fal.media/files/b/koala/mATl0lc8FwiR6WceFEDfH_692743a190bc4859a00caa338a1809c5.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/live-portrait',
    name: 'Live Portrait',
    description: 'Animate portrait images with realistic motion.',
    category: 'image-to-video',
    tags: ['portrait', 'animation'],
    thumbnailUrl: 'https://storage.googleapis.com/fal_cdn/fal/Sound-2.jpg',
    highlighted: false,
    licenseType: 'commercial',
  },
  {
    id: 'fal-ai/stable-video',
    name: 'Stable Video',
    description: 'Stable Diffusion-based image-to-video.',
    category: 'image-to-video',
    tags: ['diffusion', 'stable'],
    thumbnailUrl: 'https://storage.googleapis.com/falserverless/gallery/svd_rocket.gif',
    highlighted: false,
    licenseType: 'commercial',
  },
]

// Get all unique tags
export const allTags = Array.from(
  new Set(models.flatMap((m) => m.tags))
).filter(Boolean).sort()

// Category display names
export const categoryDisplayNames: Record<ModelCategory, string> = {
  'text-to-image': 'Text to Image',
  'text-to-video': 'Text to Video',
  'image-to-image': 'Image to Image',
  'image-to-video': 'Image to Video',
}
